name: Preview Documentation

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip3 install -U sphinx
        pip3 install sphinx_rtd_theme
        pip3 install m2r myst-parser
        pip3 install sphinx_copybutton

    - name: Build documentation
      run: cd main && make html

    - name: HTML Preview
      id: html_preview
      uses: pavi2410/html-preview-action@v2
      with:
        html_file: '_build/html'
    # - name: Deploy to preview server
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     personal_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./site
